# Terminal settings
set -g default-terminal "tmux-256color"
set -a terminal-features "tmux-256color:RGB"
set -g escape-time 0
set -g focus-events on

# Prefix and basic settings
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g mouse on

# Status bar
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
# for debugging
set -g remain-on-exit "off"

bind x kill-pane
bind r source-file "/home/florian/.tmux.conf" \; display-message "Config reloaded!"
bind b set -g status
bind-key -n M-BSpace send-keys C-w
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind a run "chezmoi apply && tmux display-message 'chezmoi apply!'"
bind A run "chezmoi apply && tmux display-message 'chezmoi apply and source tmux!' && tmux source-file ~/.tmux.conf"
bind T neww "cd $(chezmoi source-path) && nvim dot_tmux.conf"
bind H neww "cd $(chezmoi source-path) && nvim ."
bind V neww "cd $(chezmoi source-path) && nvim private_dot_config/nvim/init.lua "
bind D neww -n "docker" -S lazydocker
bind G neww -n "git" -S lazygit
bind O run "tmux neww ~/.config/scripts/open-pdf.sh"
bind g run "~/.config/scripts/open-github.sh"
bind t run "tmux neww ~/.config/scripts/time.sh"
bind K run "tmux neww ~/.config/scripts/tmux-kill-session.sh"
bind j run "tmux neww ~/.config/scripts/project-jumper.sh"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/project"
bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
bind o neww -S -n "accompamed" "nvim ~/accompamed"
bind e neww -S -n "doom" "emacs -nw"
bind E show-environment -g
